### ISSUE TITLE
Error at olive.workflows: Pydantic - To define root models, use `pydantic.RootModel` rather than a field called '__root__'

### ISSUE THREAD

**Issue by sergiosolorzano** [natke/whisper#2]
**Summary:** I get error at:
python -m olive.workflows.run --config whisper_cpu_int8.json --setup

Error: 
raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'

I have pydantic 2.1.1 and followed required installation as shown below:

**Installed packages:**
a) Environment
conda create -n whisper
pip install onnx
pip install torch
pip install transformers
pip install optimum[onnx]
pip install onnxruntime
pip install onnxruntime-extensions

b) Ort-nightly: and pip install ort-nightly==1.16.0.dev20230701001 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/

c) and installed pip install olive-ai[cpu] (also tried to no avail by removing it, to install pip install olive-ai[gpu], pip install olive-ai[directml])
Successfully installed olive-ai-0.2.1

d) cd models/whisper-tiny
pip install -r requirements.txt

-----------------------------------
**I get error:**

cd models/whisper-tiny
python prepare_whisper_configs.py --model_name openai/whisper-tiny.en
**(whisper) sergio@Ubuntu-2204-oai:~/PythonWorkspace/whisper/models/whisper-tiny$ python -m olive.workflows.run --config whisper_cpu_int8.json --setup**
**/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'json_dumps' has been removed
* 'json_loads' has been removed**
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/olive/workflows/__init__.py", line 5, in <module>
    from olive.workflows.run.run import run
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/olive/workflows/run/run.py", line 16, in <module>
    from olive.passes import Pass
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/olive/passes/__init__.py", line 5, in <module>
    from olive.passes.olive_pass import FullPassConfig, Pass
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/olive/passes/olive_pass.py", line 13, in <module>
    from olive.common.config_utils import ConfigBase, validate_config
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/olive/common/config_utils.py", line 118, in <module>
    class ConfigListBase(ConfigBase):
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 98, in __new__
    private_attributes = inspect_namespace(
  File "/home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 291, in inspect_namespace
    **raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'**
(whisper) sergio@Ubuntu-2204-oai:~/PythonWorkspace/whisper/models/whisper-tiny$ 

-----
**My setup:**
$ pip show pydantic
Name: pydantic
Version: 2.1.1
Summary: Data validation using Python type hints
Home-page: 
Author: 
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>
License: 
Location: /home/sergio/anaconda3/envs/whisper/lib/python3.10/site-packages
Requires: annotated-types, pydantic-core, typing-extensions
Required-by: olive-ai

(whisper) sergio@Ubuntu-2204-oai:~/PythonWorkspace/whisper/models/whisper-tiny$ uname -r
6.2.0-26-generic

(whisper) sergio@Ubuntu-2204-oai:~/PythonWorkspace/whisper/models/whisper-tiny$ python3 --version
Python 3.10.12

**Comment by sergiosolorzano** [comment]
Worked in another repo following https://github.com/microsoft/Olive/tree/main/examples/whisper then
python prepare_whisper_configs.py --model_name openai/whisper-tiny.en
python -m olive.workflows.run --config whisper_cpu_int8.json --setup
python -m olive.workflows.run --config whisper_cpu_int8.json
